/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/redux';
import '@ionic/core';
import 'ionicons';
import {
  Todo,
  TodoState,
} from './store/todos/types';
import {
  Action,
} from '@stencil/redux';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface TodoItem {
    'todo': Todo;
    'toggleTodo': Action;
  }
  interface TodoItemAttributes extends StencilHTMLAttributes {
    'todo'?: Todo;
    'toggleTodo'?: Action;
  }

  interface TodoList {
    'todos': TodoState;
    'toggleTodo': Action;
  }
  interface TodoListAttributes extends StencilHTMLAttributes {
    'todos'?: TodoState;
    'toggleTodo'?: Action;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppRoot': Components.AppRoot;
    'TodoItem': Components.TodoItem;
    'TodoList': Components.TodoList;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-root': Components.AppRootAttributes;
    'todo-item': Components.TodoItemAttributes;
    'todo-list': Components.TodoListAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLTodoItemElement extends Components.TodoItem, HTMLStencilElement {}
  var HTMLTodoItemElement: {
    prototype: HTMLTodoItemElement;
    new (): HTMLTodoItemElement;
  };

  interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {}
  var HTMLTodoListElement: {
    prototype: HTMLTodoListElement;
    new (): HTMLTodoListElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-root': HTMLAppRootElement
    'todo-item': HTMLTodoItemElement
    'todo-list': HTMLTodoListElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'todo-item': HTMLTodoItemElement;
    'todo-list': HTMLTodoListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
